on: 
  push:
    branches:
      - main

jobs:
  array_operations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Operations
        run: echo "Performing array operations..."
